[package]
cairo-version = "2.1.0"
name = "kakarot"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/kkrt-labs/kakarot-ssj/"
license-file = "LICENSE"

[dependencies]
starknet = "2.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.4.1" }

[[tool.starknet-contract]]
